// <auto-generated />
using System;
using Education.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Education.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    partial class EducationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Education.Domain.Audit.AdminEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorIdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActorIdentityUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventType");

                    b.ToTable("AdminEvents");
                });

            modelBuilder.Entity("Education.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("c_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Courses.CourseBindUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseBindUsers", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Courses.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("m_name");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Materials.TheoreticalMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tm_name");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lecture_text");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("TheoreticalMaterials", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Materials.TheoreticalMaterialFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<Guid>("TheoreticalMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("theoretical_material_id");

                    b.HasKey("Id");

                    b.HasIndex("TheoreticalMaterialId");

                    b.ToTable("TheoreticalMaterialFiles", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Materials.TheoreticalMaterialLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<Guid>("TheoreticalMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("theoretical_material_id");

                    b.HasKey("Id");

                    b.HasIndex("TheoreticalMaterialId");

                    b.ToTable("TheoreticalMaterialLinks", (string)null);
                });

            modelBuilder.Entity("Education.Domain.PracticalModules.PracticalModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BasePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("base_path");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IdentityAudience")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("identity_audience");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pm_name");

                    b.Property<string>("PracticeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("practice_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("PracticalModules", (string)null);
                });

            modelBuilder.Entity("Education.Domain.PracticalModules.PracticalModuleSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompletionData")
                        .HasColumnType("jsonb")
                        .HasColumnName("completion_data");

                    b.Property<string>("EndReason")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<Guid>("PracticalTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("practical_task_id");

                    b.Property<string>("ReturnUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("return_url");

                    b.Property<string>("SessionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_key");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TryNumber")
                        .HasColumnType("integer")
                        .HasColumnName("try_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PracticalTaskId");

                    b.HasIndex("UserId", "PracticalTaskId");

                    b.ToTable("PracticalModuleSessions", (string)null);
                });

            modelBuilder.Entity("Education.Domain.PracticalModules.PracticalTaskEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("PracticalTaskEvents", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Practicals.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalTaskRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_task_ref");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pm_name");

                    b.Property<Guid>("PracticalMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("practical_material_id");

                    b.Property<Guid?>("PracticalModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("practical_module_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("case_text");

                    b.HasKey("Id");

                    b.HasIndex("PracticalMaterialId");

                    b.HasIndex("PracticalModuleId");

                    b.ToTable("Cases", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Practicals.CaseFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("case_id");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("UserId");

                    b.ToTable("CaseFiles", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Practicals.CaseFileComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CaseFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_generated");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cfc_text");

                    b.HasKey("Id");

                    b.HasIndex("CaseFileId");

                    b.ToTable("CaseFileComments", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Practicals.PracticalBindUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PracticalMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("practical_material_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PracticalMaterialId");

                    b.HasIndex("UserId");

                    b.ToTable("PracticalBindUsers", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Practicals.PracticalMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pm_name");

                    b.Property<double>("PercentForFive")
                        .HasColumnType("double precision")
                        .HasColumnName("percent_for_five");

                    b.Property<double>("PercentForFour")
                        .HasColumnType("double precision")
                        .HasColumnName("percent_for_four");

                    b.Property<double>("PercentForThree")
                        .HasColumnType("double precision")
                        .HasColumnName("percent_for_three");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_minutes");

                    b.Property<int>("TriesCount")
                        .HasColumnType("integer")
                        .HasColumnName("tries_count");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("PracticalMaterials", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Tests.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answer");

                    b.Property<Guid>("PracticalMaterialBindQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("practical_material_bind_question_id");

                    b.Property<Guid>("TestResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_result_id");

                    b.HasKey("Id");

                    b.HasIndex("PracticalMaterialBindQuestionId");

                    b.HasIndex("TestResultId");

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Tests.PracticalMaterialBindQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PracticalMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("practical_material_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.HasKey("Id");

                    b.HasIndex("PracticalMaterialId");

                    b.HasIndex("QuestionId");

                    b.ToTable("PracticalMaterialBindQuestions", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Tests.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answer");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("question_body");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_type_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Tests.QuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qt_name");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Вопрос с одним ответом"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "Вопрос с несколькими ответами"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Name = "Вопрос с соотнесением"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Name = "Вопрос с вводом ответа"
                        });
                });

            modelBuilder.Entity("Education.Domain.Tests.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<double?>("MaxScore")
                        .HasColumnType("double precision")
                        .HasColumnName("max_score");

                    b.Property<Guid>("PracticalMaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("practical_material_id");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<DateTime>("StatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("TryNumber")
                        .HasColumnType("integer")
                        .HasColumnName("try_number");

                    b.Property<DateTime?>("TurnedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("turned_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PracticalMaterialId");

                    b.HasIndex("UserId");

                    b.ToTable("TestResults", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("r_name");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Преподаватель"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Студент"
                        });
                });

            modelBuilder.Entity("Education.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Education.Infrastructure.Persistence.IdentityUserLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LegacyUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("legacy_user_id");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("LegacyUserId")
                        .IsUnique();

                    b.ToTable("IdentityUserLinks", (string)null);
                });

            modelBuilder.Entity("Education.Domain.Courses.Course", b =>
                {
                    b.HasOne("Education.Domain.Users.User", "User")
                        .WithMany("Courses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Education.Domain.Courses.CourseBindUser", b =>
                {
                    b.HasOne("Education.Domain.Courses.Course", "Course")
                        .WithMany("CourseBindUsers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Education.Domain.Users.User", "User")
                        .WithMany("CourseBindUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Education.Domain.Courses.Module", b =>
                {
                    b.HasOne("Education.Domain.Courses.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Education.Domain.Materials.TheoreticalMaterial", b =>
                {
                    b.HasOne("Education.Domain.Courses.Module", "Module")
                        .WithMany("TheoreticalMaterials")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Education.Domain.Materials.TheoreticalMaterialFile", b =>
                {
                    b.HasOne("Education.Domain.Materials.TheoreticalMaterial", "TheoreticalMaterial")
                        .WithMany("Files")
                        .HasForeignKey("TheoreticalMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TheoreticalMaterial");
                });

            modelBuilder.Entity("Education.Domain.Materials.TheoreticalMaterialLink", b =>
                {
                    b.HasOne("Education.Domain.Materials.TheoreticalMaterial", "TheoreticalMaterial")
                        .WithMany("Links")
                        .HasForeignKey("TheoreticalMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TheoreticalMaterial");
                });

            modelBuilder.Entity("Education.Domain.PracticalModules.PracticalModuleSession", b =>
                {
                    b.HasOne("Education.Domain.Practicals.Case", null)
                        .WithMany()
                        .HasForeignKey("PracticalTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Education.Domain.PracticalModules.PracticalTaskEvent", b =>
                {
                    b.HasOne("Education.Domain.PracticalModules.PracticalModuleSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Education.Domain.Practicals.Case", b =>
                {
                    b.HasOne("Education.Domain.Practicals.PracticalMaterial", "PracticalMaterial")
                        .WithMany("Cases")
                        .HasForeignKey("PracticalMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Education.Domain.PracticalModules.PracticalModule", null)
                        .WithMany()
                        .HasForeignKey("PracticalModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PracticalMaterial");
                });

            modelBuilder.Entity("Education.Domain.Practicals.CaseFile", b =>
                {
                    b.HasOne("Education.Domain.Practicals.Case", "Case")
                        .WithMany("CaseFiles")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Education.Domain.Users.User", "User")
                        .WithMany("CaseFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Education.Domain.Practicals.CaseFileComment", b =>
                {
                    b.HasOne("Education.Domain.Practicals.CaseFile", "CaseFile")
                        .WithMany("Comments")
                        .HasForeignKey("CaseFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaseFile");
                });

            modelBuilder.Entity("Education.Domain.Practicals.PracticalBindUser", b =>
                {
                    b.HasOne("Education.Domain.Practicals.PracticalMaterial", "PracticalMaterial")
                        .WithMany("PracticalBindUsers")
                        .HasForeignKey("PracticalMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Education.Domain.Users.User", "User")
                        .WithMany("PracticalBindUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticalMaterial");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Education.Domain.Practicals.PracticalMaterial", b =>
                {
                    b.HasOne("Education.Domain.Courses.Module", "Module")
                        .WithMany("PracticalMaterials")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Education.Domain.Tests.Answer", b =>
                {
                    b.HasOne("Education.Domain.Tests.PracticalMaterialBindQuestion", "PracticalMaterialBindQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("PracticalMaterialBindQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Education.Domain.Tests.TestResult", "TestResult")
                        .WithMany("Answers")
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticalMaterialBindQuestion");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("Education.Domain.Tests.PracticalMaterialBindQuestion", b =>
                {
                    b.HasOne("Education.Domain.Practicals.PracticalMaterial", "PracticalMaterial")
                        .WithMany("PracticalMaterialBindQuestions")
                        .HasForeignKey("PracticalMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Education.Domain.Tests.Question", "Question")
                        .WithMany("PracticalMaterialBindQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticalMaterial");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Education.Domain.Tests.Question", b =>
                {
                    b.HasOne("Education.Domain.Courses.Module", "Module")
                        .WithMany("Questions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Education.Domain.Tests.QuestionType", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("Education.Domain.Tests.TestResult", b =>
                {
                    b.HasOne("Education.Domain.Practicals.PracticalMaterial", "PracticalMaterial")
                        .WithMany("TestResults")
                        .HasForeignKey("PracticalMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Education.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PracticalMaterial");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Education.Domain.Users.User", b =>
                {
                    b.HasOne("Education.Domain.Users.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Education.Infrastructure.Persistence.IdentityUserLink", b =>
                {
                    b.HasOne("Education.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("LegacyUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Education.Domain.Courses.Course", b =>
                {
                    b.Navigation("CourseBindUsers");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Education.Domain.Courses.Module", b =>
                {
                    b.Navigation("PracticalMaterials");

                    b.Navigation("Questions");

                    b.Navigation("TheoreticalMaterials");
                });

            modelBuilder.Entity("Education.Domain.Materials.TheoreticalMaterial", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Links");
                });

            modelBuilder.Entity("Education.Domain.Practicals.Case", b =>
                {
                    b.Navigation("CaseFiles");
                });

            modelBuilder.Entity("Education.Domain.Practicals.CaseFile", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Education.Domain.Practicals.PracticalMaterial", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("PracticalBindUsers");

                    b.Navigation("PracticalMaterialBindQuestions");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("Education.Domain.Tests.PracticalMaterialBindQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Education.Domain.Tests.Question", b =>
                {
                    b.Navigation("PracticalMaterialBindQuestions");
                });

            modelBuilder.Entity("Education.Domain.Tests.TestResult", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Education.Domain.Users.User", b =>
                {
                    b.Navigation("CaseFiles");

                    b.Navigation("CourseBindUsers");

                    b.Navigation("Courses");

                    b.Navigation("PracticalBindUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
