-- Draft migration for Prompt 04: external IdentityService user mapping.
-- This script is intentionally additive. It does not remove or rewrite Users,
-- Roles, password, role_id, or any existing FK that points to Users.id.

CREATE TABLE IF NOT EXISTS "IdentityUserLinks" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "legacy_user_id" bigint NOT NULL,
    "identity_user_id" uuid NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "is_active" boolean NOT NULL DEFAULT true,
    CONSTRAINT "FK_IdentityUserLinks_Users_legacy_user_id"
        FOREIGN KEY ("legacy_user_id")
        REFERENCES "Users" ("id")
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_IdentityUserLinks_legacy_user_id"
    ON "IdentityUserLinks" ("legacy_user_id");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_IdentityUserLinks_identity_user_id"
    ON "IdentityUserLinks" ("identity_user_id");

CREATE INDEX IF NOT EXISTS "IX_IdentityUserLinks_is_active"
    ON "IdentityUserLinks" ("is_active");

-- Backfill plan:
-- 1. Export users from IdentityService with their external Guid and stable legacy login/email.
-- 2. Import that export into a temporary staging table, for example:
--
-- CREATE TEMP TABLE "IdentityUserLinksBackfill" (
--     "legacy_login" text NOT NULL,
--     "identity_user_id" uuid NOT NULL
-- );
--
-- 3. Insert links by matching the existing Users.login value.
--
-- INSERT INTO "IdentityUserLinks" ("legacy_user_id", "identity_user_id")
-- SELECT u."id", b."identity_user_id"
-- FROM "Users" u
-- JOIN "IdentityUserLinksBackfill" b ON b."legacy_login" = u."login"
-- ON CONFLICT DO NOTHING;

-- Validation checks:

-- Users without active IdentityService mapping.
SELECT u."id", u."login"
FROM "Users" u
LEFT JOIN "IdentityUserLinks" l
    ON l."legacy_user_id" = u."id"
    AND l."is_active" = true
WHERE l."id" IS NULL;

-- Duplicate external identities, should return zero rows.
SELECT "identity_user_id", count(*)
FROM "IdentityUserLinks"
WHERE "is_active" = true
GROUP BY "identity_user_id"
HAVING count(*) > 1;

-- Duplicate legacy users, should return zero rows.
SELECT "legacy_user_id", count(*)
FROM "IdentityUserLinks"
WHERE "is_active" = true
GROUP BY "legacy_user_id"
HAVING count(*) > 1;

-- Existing user relations remain attached to Users.id.
SELECT
    u."id" AS "legacy_user_id",
    count(DISTINCT owned_courses."id") AS "owned_courses",
    count(DISTINCT course_binds."id") AS "course_binds",
    count(DISTINCT practical_binds."id") AS "practical_binds",
    count(DISTINCT case_files."id") AS "case_files",
    count(DISTINCT test_results."id") AS "test_results"
FROM "Users" u
LEFT JOIN "Courses" owned_courses ON owned_courses."user_id" = u."id"
LEFT JOIN "CourseBindUsers" course_binds ON course_binds."user_id" = u."id"
LEFT JOIN "PracticalBindUsers" practical_binds ON practical_binds."user_id" = u."id"
LEFT JOIN "CaseFiles" case_files ON case_files."user_id" = u."id"
LEFT JOIN "TestResults" test_results ON test_results."user_id" = u."id"
GROUP BY u."id"
ORDER BY u."id";
